// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: flowforge/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceStatus enumerates the lifecycle state reported by a service.
type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_STARTING    ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_HEALTHY     ServiceStatus = 2
	ServiceStatus_SERVICE_STATUS_DEGRADED    ServiceStatus = 3
	ServiceStatus_SERVICE_STATUS_UNHEALTHY   ServiceStatus = 4
	ServiceStatus_SERVICE_STATUS_STOPPING    ServiceStatus = 5
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_STARTING",
		2: "SERVICE_STATUS_HEALTHY",
		3: "SERVICE_STATUS_DEGRADED",
		4: "SERVICE_STATUS_UNHEALTHY",
		5: "SERVICE_STATUS_STOPPING",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_STATUS_STARTING":    1,
		"SERVICE_STATUS_HEALTHY":     2,
		"SERVICE_STATUS_DEGRADED":    3,
		"SERVICE_STATUS_UNHEALTHY":   4,
		"SERVICE_STATUS_STOPPING":    5,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flowforge_common_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_flowforge_common_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_flowforge_common_proto_rawDescGZIP(), []int{0}
}

// ErrorCode classifies gRPC failures so clients can decide retryability.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_ERROR_CODE_RETRYABLE   ErrorCode = 1
	ErrorCode_ERROR_CODE_PERMANENT   ErrorCode = 2
	ErrorCode_ERROR_CODE_VALIDATION  ErrorCode = 3
	ErrorCode_ERROR_CODE_INTERNAL    ErrorCode = 4
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_RETRYABLE",
		2: "ERROR_CODE_PERMANENT",
		3: "ERROR_CODE_VALIDATION",
		4: "ERROR_CODE_INTERNAL",
		5: "ERROR_CODE_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"ERROR_CODE_RETRYABLE":   1,
		"ERROR_CODE_PERMANENT":   2,
		"ERROR_CODE_VALIDATION":  3,
		"ERROR_CODE_INTERNAL":    4,
		"ERROR_CODE_UNAVAILABLE": 5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_flowforge_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_flowforge_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_flowforge_common_proto_rawDescGZIP(), []int{1}
}

// ErrorDetail carries a structured failure reason back to the caller.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=flowforge.common.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_flowforge_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_flowforge_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_flowforge_common_proto protoreflect.FileDescriptor

const file_flowforge_common_proto_rawDesc = "" +
	"\n" +
	"\x16flowforge/common.proto\x12\x10flowforge.common\"X\n" +
	"\vErrorDetail\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.flowforge.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xc0\x01\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SERVICE_STATUS_STARTING\x10\x01\x12\x1a\n" +
	"\x16SERVICE_STATUS_HEALTHY\x10\x02\x12\x1b\n" +
	"\x17SERVICE_STATUS_DEGRADED\x10\x03\x12\x1c\n" +
	"\x18SERVICE_STATUS_UNHEALTHY\x10\x04\x12\x1b\n" +
	"\x17SERVICE_STATUS_STOPPING\x10\x05*\xab\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_CODE_RETRYABLE\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_PERMANENT\x10\x02\x12\x19\n" +
	"\x15ERROR_CODE_VALIDATION\x10\x03\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x05B<Z:github.com/aman0603/flowforge/internal/proto/common;commonb\x06proto3"

var (
	file_flowforge_common_proto_rawDescOnce sync.Once
	file_flowforge_common_proto_rawDescData []byte
)

func file_flowforge_common_proto_rawDescGZIP() []byte {
	file_flowforge_common_proto_rawDescOnce.Do(func() {
		file_flowforge_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowforge_common_proto_rawDesc), len(file_flowforge_common_proto_rawDesc)))
	})
	return file_flowforge_common_proto_rawDescData
}

var file_flowforge_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flowforge_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flowforge_common_proto_goTypes = []any{
	(ServiceStatus)(0),  // 0: flowforge.common.ServiceStatus
	(ErrorCode)(0),      // 1: flowforge.common.ErrorCode
	(*ErrorDetail)(nil), // 2: flowforge.common.ErrorDetail
}
var file_flowforge_common_proto_depIdxs = []int32{
	1, // 0: flowforge.common.ErrorDetail.code:type_name -> flowforge.common.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flowforge_common_proto_init() }
func file_flowforge_common_proto_init() {
	if File_flowforge_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowforge_common_proto_rawDesc), len(file_flowforge_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowforge_common_proto_goTypes,
		DependencyIndexes: file_flowforge_common_proto_depIdxs,
		EnumInfos:         file_flowforge_common_proto_enumTypes,
		MessageInfos:      file_flowforge_common_proto_msgTypes,
	}.Build()
	File_flowforge_common_proto = out.File
	file_flowforge_common_proto_goTypes = nil
	file_flowforge_common_proto_depIdxs = nil
}
