// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: flowforge/scheduler.proto

package scheduler

import (
	common "github.com/aman0603/flowforge/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClaimedTask is the transport model for a task claimed by the scheduler.
// It intentionally does not expose the full DB row.
type ClaimedTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskRunId        string                 `protobuf:"bytes,1,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	WorkflowRunId    string                 `protobuf:"bytes,2,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	TaskDefinitionId string                 `protobuf:"bytes,3,opt,name=task_definition_id,json=taskDefinitionId,proto3" json:"task_definition_id,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TaskType         string                 `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TimeoutMs        int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FencingToken     int64                  `protobuf:"varint,7,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Input            []byte                 `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimedTask) Reset() {
	*x = ClaimedTask{}
	mi := &file_flowforge_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedTask) ProtoMessage() {}

func (x *ClaimedTask) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimedTask.ProtoReflect.Descriptor instead.
func (*ClaimedTask) Descriptor() ([]byte, []int) {
	return file_flowforge_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimedTask) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *ClaimedTask) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *ClaimedTask) GetTaskDefinitionId() string {
	if x != nil {
		return x.TaskDefinitionId
	}
	return ""
}

func (x *ClaimedTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClaimedTask) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ClaimedTask) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ClaimedTask) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ClaimedTask) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

// ClaimTasksRequest asks the scheduler to claim up to `capacity` READY tasks
// for the given worker.
type ClaimTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTasksRequest) Reset() {
	*x = ClaimTasksRequest{}
	mi := &file_flowforge_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTasksRequest) ProtoMessage() {}

func (x *ClaimTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTasksRequest.ProtoReflect.Descriptor instead.
func (*ClaimTasksRequest) Descriptor() ([]byte, []int) {
	return file_flowforge_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ClaimTasksRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// ClaimTasksResponse returns the claimed tasks.
type ClaimTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ClaimedTask         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         *common.ErrorDetail    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTasksResponse) Reset() {
	*x = ClaimTasksResponse{}
	mi := &file_flowforge_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTasksResponse) ProtoMessage() {}

func (x *ClaimTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTasksResponse.ProtoReflect.Descriptor instead.
func (*ClaimTasksResponse) Descriptor() ([]byte, []int) {
	return file_flowforge_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimTasksResponse) GetTasks() []*ClaimedTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ClaimTasksResponse) GetError() *common.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// PromoteRetriesRequest triggers promotion of due RETRY_WAIT tasks to READY.
type PromoteRetriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRetriesRequest) Reset() {
	*x = PromoteRetriesRequest{}
	mi := &file_flowforge_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRetriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRetriesRequest) ProtoMessage() {}

func (x *PromoteRetriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRetriesRequest.ProtoReflect.Descriptor instead.
func (*PromoteRetriesRequest) Descriptor() ([]byte, []int) {
	return file_flowforge_scheduler_proto_rawDescGZIP(), []int{3}
}

// PromoteRetriesResponse reports how many tasks were promoted.
type PromoteRetriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promoted      int64                  `protobuf:"varint,1,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Error         *common.ErrorDetail    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRetriesResponse) Reset() {
	*x = PromoteRetriesResponse{}
	mi := &file_flowforge_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRetriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRetriesResponse) ProtoMessage() {}

func (x *PromoteRetriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRetriesResponse.ProtoReflect.Descriptor instead.
func (*PromoteRetriesResponse) Descriptor() ([]byte, []int) {
	return file_flowforge_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *PromoteRetriesResponse) GetPromoted() int64 {
	if x != nil {
		return x.Promoted
	}
	return 0
}

func (x *PromoteRetriesResponse) GetError() *common.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_flowforge_scheduler_proto protoreflect.FileDescriptor

const file_flowforge_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19flowforge/scheduler.proto\x12\x13flowforge.scheduler\x1a\x16flowforge/common.proto\"\x8e\x02\n" +
	"\vClaimedTask\x12\x1e\n" +
	"\vtask_run_id\x18\x01 \x01(\tR\ttaskRunId\x12&\n" +
	"\x0fworkflow_run_id\x18\x02 \x01(\tR\rworkflowRunId\x12,\n" +
	"\x12task_definition_id\x18\x03 \x01(\tR\x10taskDefinitionId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\ttask_type\x18\x05 \x01(\tR\btaskType\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12#\n" +
	"\rfencing_token\x18\a \x01(\x03R\ffencingToken\x12\x14\n" +
	"\x05input\x18\b \x01(\fR\x05input\"L\n" +
	"\x11ClaimTasksRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\"\x81\x01\n" +
	"\x12ClaimTasksResponse\x126\n" +
	"\x05tasks\x18\x01 \x03(\v2 .flowforge.scheduler.ClaimedTaskR\x05tasks\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1d.flowforge.common.ErrorDetailR\x05error\"\x17\n" +
	"\x15PromoteRetriesRequest\"i\n" +
	"\x16PromoteRetriesResponse\x12\x1a\n" +
	"\bpromoted\x18\x01 \x01(\x03R\bpromoted\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1d.flowforge.common.ErrorDetailR\x05error2\xdc\x01\n" +
	"\x10SchedulerService\x12]\n" +
	"\n" +
	"ClaimTasks\x12&.flowforge.scheduler.ClaimTasksRequest\x1a'.flowforge.scheduler.ClaimTasksResponse\x12i\n" +
	"\x0ePromoteRetries\x12*.flowforge.scheduler.PromoteRetriesRequest\x1a+.flowforge.scheduler.PromoteRetriesResponseBBZ@github.com/aman0603/flowforge/internal/proto/scheduler;schedulerb\x06proto3"

var (
	file_flowforge_scheduler_proto_rawDescOnce sync.Once
	file_flowforge_scheduler_proto_rawDescData []byte
)

func file_flowforge_scheduler_proto_rawDescGZIP() []byte {
	file_flowforge_scheduler_proto_rawDescOnce.Do(func() {
		file_flowforge_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowforge_scheduler_proto_rawDesc), len(file_flowforge_scheduler_proto_rawDesc)))
	})
	return file_flowforge_scheduler_proto_rawDescData
}

var file_flowforge_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flowforge_scheduler_proto_goTypes = []any{
	(*ClaimedTask)(nil),            // 0: flowforge.scheduler.ClaimedTask
	(*ClaimTasksRequest)(nil),      // 1: flowforge.scheduler.ClaimTasksRequest
	(*ClaimTasksResponse)(nil),     // 2: flowforge.scheduler.ClaimTasksResponse
	(*PromoteRetriesRequest)(nil),  // 3: flowforge.scheduler.PromoteRetriesRequest
	(*PromoteRetriesResponse)(nil), // 4: flowforge.scheduler.PromoteRetriesResponse
	(*common.ErrorDetail)(nil),     // 5: flowforge.common.ErrorDetail
}
var file_flowforge_scheduler_proto_depIdxs = []int32{
	0, // 0: flowforge.scheduler.ClaimTasksResponse.tasks:type_name -> flowforge.scheduler.ClaimedTask
	5, // 1: flowforge.scheduler.ClaimTasksResponse.error:type_name -> flowforge.common.ErrorDetail
	5, // 2: flowforge.scheduler.PromoteRetriesResponse.error:type_name -> flowforge.common.ErrorDetail
	1, // 3: flowforge.scheduler.SchedulerService.ClaimTasks:input_type -> flowforge.scheduler.ClaimTasksRequest
	3, // 4: flowforge.scheduler.SchedulerService.PromoteRetries:input_type -> flowforge.scheduler.PromoteRetriesRequest
	2, // 5: flowforge.scheduler.SchedulerService.ClaimTasks:output_type -> flowforge.scheduler.ClaimTasksResponse
	4, // 6: flowforge.scheduler.SchedulerService.PromoteRetries:output_type -> flowforge.scheduler.PromoteRetriesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_flowforge_scheduler_proto_init() }
func file_flowforge_scheduler_proto_init() {
	if File_flowforge_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowforge_scheduler_proto_rawDesc), len(file_flowforge_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flowforge_scheduler_proto_goTypes,
		DependencyIndexes: file_flowforge_scheduler_proto_depIdxs,
		MessageInfos:      file_flowforge_scheduler_proto_msgTypes,
	}.Build()
	File_flowforge_scheduler_proto = out.File
	file_flowforge_scheduler_proto_goTypes = nil
	file_flowforge_scheduler_proto_depIdxs = nil
}
