// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: flowforge/health.proto

package health

import (
	common "github.com/aman0603/flowforge/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest is sent by a client probing a service's liveness/readiness.
type HealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true the caller is asking for readiness (can serve traffic),
	// otherwise liveness (process is up).
	Readiness     bool `protobuf:"varint,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_flowforge_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_flowforge_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetReadiness() bool {
	if x != nil {
		return x.Readiness
	}
	return false
}

// HealthResponse reports the probed service state.
type HealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status common.ServiceStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=flowforge.common.ServiceStatus" json:"status,omitempty"`
	// Optional free-form detail (e.g. "redis unreachable").
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_flowforge_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_flowforge_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() common.ServiceStatus {
	if x != nil {
		return x.Status
	}
	return common.ServiceStatus(0)
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_flowforge_health_proto protoreflect.FileDescriptor

const file_flowforge_health_proto_rawDesc = "" +
	"\n" +
	"\x16flowforge/health.proto\x12\x10flowforge.health\x1a\x16flowforge/common.proto\"-\n" +
	"\rHealthRequest\x12\x1c\n" +
	"\treadiness\x18\x01 \x01(\bR\treadiness\"a\n" +
	"\x0eHealthResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.flowforge.common.ServiceStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail2[\n" +
	"\rHealthService\x12J\n" +
	"\x05Check\x12\x1f.flowforge.health.HealthRequest\x1a .flowforge.health.HealthResponseB<Z:github.com/aman0603/flowforge/internal/proto/health;healthb\x06proto3"

var (
	file_flowforge_health_proto_rawDescOnce sync.Once
	file_flowforge_health_proto_rawDescData []byte
)

func file_flowforge_health_proto_rawDescGZIP() []byte {
	file_flowforge_health_proto_rawDescOnce.Do(func() {
		file_flowforge_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowforge_health_proto_rawDesc), len(file_flowforge_health_proto_rawDesc)))
	})
	return file_flowforge_health_proto_rawDescData
}

var file_flowforge_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flowforge_health_proto_goTypes = []any{
	(*HealthRequest)(nil),     // 0: flowforge.health.HealthRequest
	(*HealthResponse)(nil),    // 1: flowforge.health.HealthResponse
	(common.ServiceStatus)(0), // 2: flowforge.common.ServiceStatus
}
var file_flowforge_health_proto_depIdxs = []int32{
	2, // 0: flowforge.health.HealthResponse.status:type_name -> flowforge.common.ServiceStatus
	0, // 1: flowforge.health.HealthService.Check:input_type -> flowforge.health.HealthRequest
	1, // 2: flowforge.health.HealthService.Check:output_type -> flowforge.health.HealthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flowforge_health_proto_init() }
func file_flowforge_health_proto_init() {
	if File_flowforge_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowforge_health_proto_rawDesc), len(file_flowforge_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flowforge_health_proto_goTypes,
		DependencyIndexes: file_flowforge_health_proto_depIdxs,
		MessageInfos:      file_flowforge_health_proto_msgTypes,
	}.Build()
	File_flowforge_health_proto = out.File
	file_flowforge_health_proto_goTypes = nil
	file_flowforge_health_proto_depIdxs = nil
}
