// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: flowforge/recovery.proto

package recovery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecoveryService_RecoverTask_FullMethodName       = "/flowforge.recovery.RecoveryService/RecoverTask"
	RecoveryService_RecoverStaleTasks_FullMethodName = "/flowforge.recovery.RecoveryService/RecoverStaleTasks"
)

// RecoveryServiceClient is the client API for RecoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecoveryService owns lease-aware stale recovery and retry promotion. It does
// NOT execute tasks. It is called synchronously by the Worker service over gRPC.
type RecoveryServiceClient interface {
	RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*RecoverTaskResponse, error)
	RecoverStaleTasks(ctx context.Context, in *RecoverStaleTasksRequest, opts ...grpc.CallOption) (*RecoverStaleTasksResponse, error)
}

type recoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoveryServiceClient(cc grpc.ClientConnInterface) RecoveryServiceClient {
	return &recoveryServiceClient{cc}
}

func (c *recoveryServiceClient) RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*RecoverTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverTaskResponse)
	err := c.cc.Invoke(ctx, RecoveryService_RecoverTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoveryServiceClient) RecoverStaleTasks(ctx context.Context, in *RecoverStaleTasksRequest, opts ...grpc.CallOption) (*RecoverStaleTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverStaleTasksResponse)
	err := c.cc.Invoke(ctx, RecoveryService_RecoverStaleTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecoveryServiceServer is the server API for RecoveryService service.
// All implementations must embed UnimplementedRecoveryServiceServer
// for forward compatibility.
//
// RecoveryService owns lease-aware stale recovery and retry promotion. It does
// NOT execute tasks. It is called synchronously by the Worker service over gRPC.
type RecoveryServiceServer interface {
	RecoverTask(context.Context, *RecoverTaskRequest) (*RecoverTaskResponse, error)
	RecoverStaleTasks(context.Context, *RecoverStaleTasksRequest) (*RecoverStaleTasksResponse, error)
	mustEmbedUnimplementedRecoveryServiceServer()
}

// UnimplementedRecoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecoveryServiceServer struct{}

func (UnimplementedRecoveryServiceServer) RecoverTask(context.Context, *RecoverTaskRequest) (*RecoverTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverTask not implemented")
}
func (UnimplementedRecoveryServiceServer) RecoverStaleTasks(context.Context, *RecoverStaleTasksRequest) (*RecoverStaleTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverStaleTasks not implemented")
}
func (UnimplementedRecoveryServiceServer) mustEmbedUnimplementedRecoveryServiceServer() {}
func (UnimplementedRecoveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRecoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoveryServiceServer will
// result in compilation errors.
type UnsafeRecoveryServiceServer interface {
	mustEmbedUnimplementedRecoveryServiceServer()
}

func RegisterRecoveryServiceServer(s grpc.ServiceRegistrar, srv RecoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedRecoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecoveryService_ServiceDesc, srv)
}

func _RecoveryService_RecoverTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoveryServiceServer).RecoverTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecoveryService_RecoverTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoveryServiceServer).RecoverTask(ctx, req.(*RecoverTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecoveryService_RecoverStaleTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStaleTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoveryServiceServer).RecoverStaleTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecoveryService_RecoverStaleTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoveryServiceServer).RecoverStaleTasks(ctx, req.(*RecoverStaleTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecoveryService_ServiceDesc is the grpc.ServiceDesc for RecoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowforge.recovery.RecoveryService",
	HandlerType: (*RecoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoverTask",
			Handler:    _RecoveryService_RecoverTask_Handler,
		},
		{
			MethodName: "RecoverStaleTasks",
			Handler:    _RecoveryService_RecoverStaleTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flowforge/recovery.proto",
}
