// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: flowforge/recovery.proto

package recovery

import (
	common "github.com/aman0603/flowforge/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecoverTaskRequest asks the Recovery service to reclaim a single stale task.
// The caller (Worker) is responsible for the Redis lease/worker-aliveness gate
// before invoking this; the service performs the guarded, fencing-token-checked
// database transition.
type RecoverTaskRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskRunId    string                 `protobuf:"bytes,1,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	FencingToken int64                  `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// task_status is the stale status observed by the caller ("CLAIMED"/"RUNNING").
	TaskStatus    string `protobuf:"bytes,3,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverTaskRequest) Reset() {
	*x = RecoverTaskRequest{}
	mi := &file_flowforge_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverTaskRequest) ProtoMessage() {}

func (x *RecoverTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverTaskRequest.ProtoReflect.Descriptor instead.
func (*RecoverTaskRequest) Descriptor() ([]byte, []int) {
	return file_flowforge_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *RecoverTaskRequest) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *RecoverTaskRequest) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *RecoverTaskRequest) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

// RecoverTaskResponse reports whether the task was actually reclaimed.
type RecoverTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reclaimed     bool                   `protobuf:"varint,1,opt,name=reclaimed,proto3" json:"reclaimed,omitempty"`
	Error         *common.ErrorDetail    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverTaskResponse) Reset() {
	*x = RecoverTaskResponse{}
	mi := &file_flowforge_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverTaskResponse) ProtoMessage() {}

func (x *RecoverTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverTaskResponse.ProtoReflect.Descriptor instead.
func (*RecoverTaskResponse) Descriptor() ([]byte, []int) {
	return file_flowforge_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RecoverTaskResponse) GetReclaimed() bool {
	if x != nil {
		return x.Reclaimed
	}
	return false
}

func (x *RecoverTaskResponse) GetError() *common.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// RecoverStaleTasksRequest triggers a full stale-task sweep on the Recovery
// service. It is used when the Worker delegates the entire recovery loop.
type RecoverStaleTasksRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClaimedTimeoutMs int64                  `protobuf:"varint,1,opt,name=claimed_timeout_ms,json=claimedTimeoutMs,proto3" json:"claimed_timeout_ms,omitempty"`
	RunningTimeoutMs int64                  `protobuf:"varint,2,opt,name=running_timeout_ms,json=runningTimeoutMs,proto3" json:"running_timeout_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoverStaleTasksRequest) Reset() {
	*x = RecoverStaleTasksRequest{}
	mi := &file_flowforge_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverStaleTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverStaleTasksRequest) ProtoMessage() {}

func (x *RecoverStaleTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverStaleTasksRequest.ProtoReflect.Descriptor instead.
func (*RecoverStaleTasksRequest) Descriptor() ([]byte, []int) {
	return file_flowforge_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *RecoverStaleTasksRequest) GetClaimedTimeoutMs() int64 {
	if x != nil {
		return x.ClaimedTimeoutMs
	}
	return 0
}

func (x *RecoverStaleTasksRequest) GetRunningTimeoutMs() int64 {
	if x != nil {
		return x.RunningTimeoutMs
	}
	return 0
}

// RecoverStaleTasksResponse reports how many tasks were reclaimed.
type RecoverStaleTasksResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClaimedRecovered int64                  `protobuf:"varint,1,opt,name=claimed_recovered,json=claimedRecovered,proto3" json:"claimed_recovered,omitempty"`
	RunningRecovered int64                  `protobuf:"varint,2,opt,name=running_recovered,json=runningRecovered,proto3" json:"running_recovered,omitempty"`
	Error            *common.ErrorDetail    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoverStaleTasksResponse) Reset() {
	*x = RecoverStaleTasksResponse{}
	mi := &file_flowforge_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverStaleTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverStaleTasksResponse) ProtoMessage() {}

func (x *RecoverStaleTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowforge_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverStaleTasksResponse.ProtoReflect.Descriptor instead.
func (*RecoverStaleTasksResponse) Descriptor() ([]byte, []int) {
	return file_flowforge_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *RecoverStaleTasksResponse) GetClaimedRecovered() int64 {
	if x != nil {
		return x.ClaimedRecovered
	}
	return 0
}

func (x *RecoverStaleTasksResponse) GetRunningRecovered() int64 {
	if x != nil {
		return x.RunningRecovered
	}
	return 0
}

func (x *RecoverStaleTasksResponse) GetError() *common.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_flowforge_recovery_proto protoreflect.FileDescriptor

const file_flowforge_recovery_proto_rawDesc = "" +
	"\n" +
	"\x18flowforge/recovery.proto\x12\x12flowforge.recovery\x1a\x16flowforge/common.proto\"z\n" +
	"\x12RecoverTaskRequest\x12\x1e\n" +
	"\vtask_run_id\x18\x01 \x01(\tR\ttaskRunId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x03R\ffencingToken\x12\x1f\n" +
	"\vtask_status\x18\x03 \x01(\tR\n" +
	"taskStatus\"h\n" +
	"\x13RecoverTaskResponse\x12\x1c\n" +
	"\treclaimed\x18\x01 \x01(\bR\treclaimed\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1d.flowforge.common.ErrorDetailR\x05error\"v\n" +
	"\x18RecoverStaleTasksRequest\x12,\n" +
	"\x12claimed_timeout_ms\x18\x01 \x01(\x03R\x10claimedTimeoutMs\x12,\n" +
	"\x12running_timeout_ms\x18\x02 \x01(\x03R\x10runningTimeoutMs\"\xaa\x01\n" +
	"\x19RecoverStaleTasksResponse\x12+\n" +
	"\x11claimed_recovered\x18\x01 \x01(\x03R\x10claimedRecovered\x12+\n" +
	"\x11running_recovered\x18\x02 \x01(\x03R\x10runningRecovered\x123\n" +
	"\x05error\x18\x03 \x01(\v2\x1d.flowforge.common.ErrorDetailR\x05error2\xe3\x01\n" +
	"\x0fRecoveryService\x12^\n" +
	"\vRecoverTask\x12&.flowforge.recovery.RecoverTaskRequest\x1a'.flowforge.recovery.RecoverTaskResponse\x12p\n" +
	"\x11RecoverStaleTasks\x12,.flowforge.recovery.RecoverStaleTasksRequest\x1a-.flowforge.recovery.RecoverStaleTasksResponseB@Z>github.com/aman0603/flowforge/internal/proto/recovery;recoveryb\x06proto3"

var (
	file_flowforge_recovery_proto_rawDescOnce sync.Once
	file_flowforge_recovery_proto_rawDescData []byte
)

func file_flowforge_recovery_proto_rawDescGZIP() []byte {
	file_flowforge_recovery_proto_rawDescOnce.Do(func() {
		file_flowforge_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowforge_recovery_proto_rawDesc), len(file_flowforge_recovery_proto_rawDesc)))
	})
	return file_flowforge_recovery_proto_rawDescData
}

var file_flowforge_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_flowforge_recovery_proto_goTypes = []any{
	(*RecoverTaskRequest)(nil),        // 0: flowforge.recovery.RecoverTaskRequest
	(*RecoverTaskResponse)(nil),       // 1: flowforge.recovery.RecoverTaskResponse
	(*RecoverStaleTasksRequest)(nil),  // 2: flowforge.recovery.RecoverStaleTasksRequest
	(*RecoverStaleTasksResponse)(nil), // 3: flowforge.recovery.RecoverStaleTasksResponse
	(*common.ErrorDetail)(nil),        // 4: flowforge.common.ErrorDetail
}
var file_flowforge_recovery_proto_depIdxs = []int32{
	4, // 0: flowforge.recovery.RecoverTaskResponse.error:type_name -> flowforge.common.ErrorDetail
	4, // 1: flowforge.recovery.RecoverStaleTasksResponse.error:type_name -> flowforge.common.ErrorDetail
	0, // 2: flowforge.recovery.RecoveryService.RecoverTask:input_type -> flowforge.recovery.RecoverTaskRequest
	2, // 3: flowforge.recovery.RecoveryService.RecoverStaleTasks:input_type -> flowforge.recovery.RecoverStaleTasksRequest
	1, // 4: flowforge.recovery.RecoveryService.RecoverTask:output_type -> flowforge.recovery.RecoverTaskResponse
	3, // 5: flowforge.recovery.RecoveryService.RecoverStaleTasks:output_type -> flowforge.recovery.RecoverStaleTasksResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flowforge_recovery_proto_init() }
func file_flowforge_recovery_proto_init() {
	if File_flowforge_recovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowforge_recovery_proto_rawDesc), len(file_flowforge_recovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flowforge_recovery_proto_goTypes,
		DependencyIndexes: file_flowforge_recovery_proto_depIdxs,
		MessageInfos:      file_flowforge_recovery_proto_msgTypes,
	}.Build()
	File_flowforge_recovery_proto = out.File
	file_flowforge_recovery_proto_goTypes = nil
	file_flowforge_recovery_proto_depIdxs = nil
}
